# .github/workflows/daily-twitter-bot.yml

name: Daily Twitter Bot

on:
  schedule:
    # Run daily at 8:00 PM UTC
    - cron: '0 20 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  run-twitter-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy scikit-learn
      
      - name: Run Twitter bot
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python main.py
      
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add results/
          git diff --quiet && git diff --staged --quiet || git commit -m "Add daily results for $(date +'%Y-%m-%d')"
          git push
